### ISSUE TITLE
Logback converter for Backspace character

### ISSUE THREAD

**Issue by iam-nagarajan** [augustd/owasp-security-logging#75]
Right now we have CRLFConverter to replace newline and carriage return with underscore, which prevents CRLF log injection.
Do we have a way to prevent Backspace injection into the logs?

**Comment by spoofzu** [comment]
Seems like the minimalist method to fix this for now is...
1) Stop using CRLFConverter.  Use instead NLFConverter.
2) Update Util.escapeNLFChars(String) to include Backspace.  Add the following new improvement...
// BS
.replace("\u0008", "\\u0008)
3) Update unit test, UtilsTest. escapeNLFCharsShouldEscapeAllNLF().  Add the following test improvement...
Assert.assertEquals("line0\\u0008line1", Utils.escapeNLFChars("line0\u0008line1"));
Compile and test.
Does it work ok?  If so, let us know.  A bonus: send us a pull request if it works.  ;o)

**Comment by spoofzu** [comment]
I see you sent the pull request.  I suspect your back on track again.  How did that work for you?

**Comment by iam-nagarajan** [comment]
HI @spoofzu yes, I have verified this. Tried with this sample message "\btest\r\nINFO Creating new log", all these special characters were escaped. Earlier only \r\n was escaped, \b resulted in removing a character before that.
